[debug] [2018-08-18T15:28:24.191Z] ----------------------------------------------------------------------
[debug] [2018-08-18T15:28:24.202Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login
[debug] [2018-08-18T15:28:24.203Z] CLI Version:   3.18.4
[debug] [2018-08-18T15:28:24.203Z] Platform:      win32
[debug] [2018-08-18T15:28:24.203Z] Node Version:  v8.9.0
[debug] [2018-08-18T15:28:24.205Z] Time:          Sat Aug 18 2018 16:28:24 GMT+0100 (Afr. centrale Ouest)
[debug] [2018-08-18T15:28:24.206Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=31259969&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-08-18T15:28:52.978Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/PwBVTnTPLlL70oPUg5gMbb43_-mLrHmqlJwj6RgAkwoz1hJiXs5v9Ux4VFof_9QbCqGO_TagHsIbPIoq1IGDJ_c',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Sat Aug 18 2018 16:28:52 GMT+0100 (Afr. centrale Ouest)
[debug] [2018-08-18T15:28:54.531Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-08-18T15:29:30.066Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/PwAwHZpLiyPE_-cx-O2ClFgfbecB2ocxND4hbqWtaoITQ-2waAnf27--6qmr_OoMowsRXgjd-IIyIaONl3U527o',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Sat Aug 18 2018 16:29:30 GMT+0100 (Afr. centrale Ouest)
[debug] [2018-08-18T15:29:30.411Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-08-18T15:40:37.161Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/PwB6Uj6e3hVoj_ELrmOU-RmT8qbiBOdwsxOlNC7K5UhCmUDhkWIzokiLYnGJvxdy8BzNOdXljuT5g3AgA-FbY_w',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Sat Aug 18 2018 16:40:37 GMT+0100 (Afr. centrale Ouest)
[debug] [2018-08-18T15:40:37.748Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-08-18T16:07:51.168Z] ----------------------------------------------------------------------
[debug] [2018-08-18T16:07:51.181Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login
[debug] [2018-08-18T16:07:51.182Z] CLI Version:   3.18.4
[debug] [2018-08-18T16:07:51.182Z] Platform:      win32
[debug] [2018-08-18T16:07:51.183Z] Node Version:  v8.9.0
[debug] [2018-08-18T16:07:51.184Z] Time:          Sat Aug 18 2018 17:07:51 GMT+0100 (Afr. centrale Ouest)
[debug] [2018-08-18T16:07:51.185Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=871466488&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-08-18T16:08:10.975Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/PwAZHP1fVyBb4K3Co1VOQQZR1gY5u4YSHKfnV0OsY5p5Nr9F4uHTMHT04uPF34Xfo4Ul-aRbFQrDdundZoDZ440',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Sat Aug 18 2018 17:08:10 GMT+0100 (Afr. centrale Ouest)
[debug] [2018-08-18T16:08:11.942Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-08-18T17:03:57.010Z] ----------------------------------------------------------------------
[debug] [2018-08-18T17:03:57.018Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login
[debug] [2018-08-18T17:03:57.019Z] CLI Version:   3.18.4
[debug] [2018-08-18T17:03:57.019Z] Platform:      win32
[debug] [2018-08-18T17:03:57.019Z] Node Version:  v8.9.0
[debug] [2018-08-18T17:03:57.021Z] Time:          Sat Aug 18 2018 18:03:57 GMT+0100 (Afr. centrale Ouest)
[debug] [2018-08-18T17:03:57.021Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=757131860&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-08-18T17:05:37.558Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/PwCT_yIYgy5zy2LxI_Q9PJvzEe7ahgeEGKmwLx2XzPVbRet6Y9aCzKd3VGPa_CzebWLpZK6AZ4Nwmb3zkvmHlTY',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Sat Aug 18 2018 18:05:37 GMT+0100 (Afr. centrale Ouest)
[debug] [2018-08-18T17:05:38.439Z] Token Fetch Error: Error
    at new FirebaseError (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\kevmax\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
